{% set name = "python-coreapi" %}
{% set pypi_name = "coreapi" %}
{% set version = "2.3.3" %}
{% set sha256 = "46145fcc1f7017c076a2ef684969b641d18a2991051fddec9458ad3f78ffc1cb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - requests
    - uritemplate
    - python-coreschema
    - itypes

test:
  requires:
    - python {{ python_min }}
  imports:
    - coreapi

about:
  home: http://core-api.github.io/python-client/
  license: BSD
  license_family: BSD
  # No license file available, but setup.py claims BSD. Issue opened in repo
  #license_file: LICENSE.txt
  summary: 'Python client library for Core API.'
  doc_url: http://core-api.github.io/python-client/
  dev_url: https://github.com/core-api/python-client

extra:
  recipe-maintainers:
    - scopatz
